[build]
  command = "remix build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[context.production.plugins]]
package = "@netlify/plugin-lighthouse"

# to audit a specific absolute url
[[context.production.plugins.inputs.audits]]
  url = "https://www.brannen.dev"


